// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/token/card/card.proto

package token

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,proto3" json:"card_number,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TokenData     string                 `protobuf:"bytes,4,opt,name=token_data,proto3" json:"token_data,omitempty"`
	CreateAt      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=create_at,json=created_at,proto3" json:"create_at,omitempty"`
	ExpireAt      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=expire_at,json=expired_at,proto3" json:"expire_at,omitempty"`
	UpdateAt      *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=update_at,json=updated_at,proto3" json:"update_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_token_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_token_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Card) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Card) GetTokenData() string {
	if x != nil {
		return x.TokenData
	}
	return ""
}

func (x *Card) GetCreateAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *Card) GetExpireAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *Card) GetUpdateAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

type CardTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardTokenRequest) Reset() {
	*x = CardTokenRequest{}
	mi := &file_proto_token_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardTokenRequest) ProtoMessage() {}

func (x *CardTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardTokenRequest.ProtoReflect.Descriptor instead.
func (*CardTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *CardTokenRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type CardTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardTokenResponse) Reset() {
	*x = CardTokenResponse{}
	mi := &file_proto_token_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardTokenResponse) ProtoMessage() {}

func (x *CardTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardTokenResponse.ProtoReflect.Descriptor instead.
func (*CardTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *CardTokenResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListCardTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardTokenResponse) Reset() {
	*x = ListCardTokenResponse{}
	mi := &file_proto_token_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardTokenResponse) ProtoMessage() {}

func (x *ListCardTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardTokenResponse.ProtoReflect.Descriptor instead.
func (*ListCardTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *ListCardTokenResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_proto_token_card_card_proto protoreflect.FileDescriptor

const file_proto_token_card_card_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/token/card/card.proto\x12\x05token\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vcard_number\x18\x02 \x01(\tR\vcard_number\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"token_data\x18\x04 \x01(\tR\n" +
	"token_data\x129\n" +
	"\tcreate_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x129\n" +
	"\texpire_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expired_at\x129\n" +
	"\tupdate_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"3\n" +
	"\x10CardTokenRequest\x12\x1f\n" +
	"\x04card\x18\x01 \x01(\v2\v.token.CardR\x04card\"4\n" +
	"\x11CardTokenResponse\x12\x1f\n" +
	"\x04card\x18\x01 \x01(\v2\v.token.CardR\x04card\":\n" +
	"\x15ListCardTokenResponse\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.token.CardR\x05cardsB4Z2github.com/eliezerraj/go-grpc-proto/protogen/tokenb\x06proto3"

var (
	file_proto_token_card_card_proto_rawDescOnce sync.Once
	file_proto_token_card_card_proto_rawDescData []byte
)

func file_proto_token_card_card_proto_rawDescGZIP() []byte {
	file_proto_token_card_card_proto_rawDescOnce.Do(func() {
		file_proto_token_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_card_card_proto_rawDesc), len(file_proto_token_card_card_proto_rawDesc)))
	})
	return file_proto_token_card_card_proto_rawDescData
}

var file_proto_token_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_token_card_card_proto_goTypes = []any{
	(*Card)(nil),                  // 0: token.Card
	(*CardTokenRequest)(nil),      // 1: token.CardTokenRequest
	(*CardTokenResponse)(nil),     // 2: token.CardTokenResponse
	(*ListCardTokenResponse)(nil), // 3: token.ListCardTokenResponse
	(*timestamp.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_proto_token_card_card_proto_depIdxs = []int32{
	4, // 0: token.Card.create_at:type_name -> google.protobuf.Timestamp
	4, // 1: token.Card.expire_at:type_name -> google.protobuf.Timestamp
	4, // 2: token.Card.update_at:type_name -> google.protobuf.Timestamp
	0, // 3: token.CardTokenRequest.card:type_name -> token.Card
	0, // 4: token.CardTokenResponse.card:type_name -> token.Card
	0, // 5: token.ListCardTokenResponse.cards:type_name -> token.Card
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_token_card_card_proto_init() }
func file_proto_token_card_card_proto_init() {
	if File_proto_token_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_card_card_proto_rawDesc), len(file_proto_token_card_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_token_card_card_proto_goTypes,
		DependencyIndexes: file_proto_token_card_card_proto_depIdxs,
		MessageInfos:      file_proto_token_card_card_proto_msgTypes,
	}.Build()
	File_proto_token_card_card_proto = out.File
	file_proto_token_card_card_proto_goTypes = nil
	file_proto_token_card_card_proto_depIdxs = nil
}
