// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/token/pod/pod.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pod struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PodName          string                 `protobuf:"bytes,2,opt,name=pod_name,proto3" json:"pod_name,omitempty"`
	IpAddress        string                 `protobuf:"bytes,3,opt,name=ip_address,proto3" json:"ip_address,omitempty"`
	Host             string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,5,opt,name=availability_zone,proto3" json:"availability_zone,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_proto_token_pod_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_pod_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_proto_token_pod_pod_proto_rawDescGZIP(), []int{0}
}

func (x *Pod) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Pod) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Pod) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Pod) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Pod) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

type PodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRequest) Reset() {
	*x = PodRequest{}
	mi := &file_proto_token_pod_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRequest) ProtoMessage() {}

func (x *PodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_pod_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRequest.ProtoReflect.Descriptor instead.
func (*PodRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_pod_pod_proto_rawDescGZIP(), []int{1}
}

type PodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *Pod                   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodResponse) Reset() {
	*x = PodResponse{}
	mi := &file_proto_token_pod_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodResponse) ProtoMessage() {}

func (x *PodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_pod_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodResponse.ProtoReflect.Descriptor instead.
func (*PodResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_pod_pod_proto_rawDescGZIP(), []int{2}
}

func (x *PodResponse) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

var File_proto_token_pod_pod_proto protoreflect.FileDescriptor

const file_proto_token_pod_pod_proto_rawDesc = "" +
	"\n" +
	"\x19proto/token/pod/pod.proto\x12\x05token\"\x9d\x01\n" +
	"\x03Pod\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bpod_name\x18\x02 \x01(\tR\bpod_name\x12\x1e\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\n" +
	"ip_address\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12,\n" +
	"\x11availability_zone\x18\x05 \x01(\tR\x11availability_zone\"\f\n" +
	"\n" +
	"PodRequest\"+\n" +
	"\vPodResponse\x12\x1c\n" +
	"\x03pod\x18\x01 \x01(\v2\n" +
	".token.PodR\x03podB4Z2github.com/eliezerraj/go-grpc-proto/protogen/tokenb\x06proto3"

var (
	file_proto_token_pod_pod_proto_rawDescOnce sync.Once
	file_proto_token_pod_pod_proto_rawDescData []byte
)

func file_proto_token_pod_pod_proto_rawDescGZIP() []byte {
	file_proto_token_pod_pod_proto_rawDescOnce.Do(func() {
		file_proto_token_pod_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_pod_pod_proto_rawDesc), len(file_proto_token_pod_pod_proto_rawDesc)))
	})
	return file_proto_token_pod_pod_proto_rawDescData
}

var file_proto_token_pod_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_token_pod_pod_proto_goTypes = []any{
	(*Pod)(nil),         // 0: token.Pod
	(*PodRequest)(nil),  // 1: token.PodRequest
	(*PodResponse)(nil), // 2: token.PodResponse
}
var file_proto_token_pod_pod_proto_depIdxs = []int32{
	0, // 0: token.PodResponse.pod:type_name -> token.Pod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_token_pod_pod_proto_init() }
func file_proto_token_pod_pod_proto_init() {
	if File_proto_token_pod_pod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_pod_pod_proto_rawDesc), len(file_proto_token_pod_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_token_pod_pod_proto_goTypes,
		DependencyIndexes: file_proto_token_pod_pod_proto_depIdxs,
		MessageInfos:      file_proto_token_pod_pod_proto_msgTypes,
	}.Build()
	File_proto_token_pod_pod_proto = out.File
	file_proto_token_pod_pod_proto_goTypes = nil
	file_proto_token_pod_pod_proto_depIdxs = nil
}
