apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: &app-name go-tokenization-grpc-hpa
  namespace: test-a
  labels:
    app: *app-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-tokenization-grpc
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods #Percent
        value: 1 #100
        periodSeconds: 15  
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
